Audit log Maintenance Automation test
LabKey/testAutomation pull request #1457
Opened 2023-03-31 06:12 UTC by labkey-sweta

#### Rationale
Automation test for Audit log cleanup

https://docs.google.com/document/d/1c4Fcbth-IW1msqhqzO8jwxik3ZwfTEfKL-uSN0n2sAc/edit#
#### Related Pull Requests
* 

#### Changes
*

2023-03-31 21:21 UTC, labkey-tchad requested changes
Looks like this functionality comes from the `professional` module. This test and page belong in that repository.

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/pages/core/admin/AuditLogMaintenancePage.java
> +        waitForPage();
The `LabKeyPage` default constructor calls `waitForPage`, no need to call it again here.
```suggestion
        super(driver);
```

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/pages/core/admin/AuditLogMaintenancePage.java
> +    }
Do save and cancel trigger page loads?
```suggestion
    public void clickSave()
    {
        clickAndWait(elementCache().saveBtn);
    }

    public void clickCancel()
    {
        clickAndWait(elementCache().cancelBtn);
    }
```

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/pages/core/admin/AuditLogMaintenancePage.java
> +    }
`getText` doesn't work like this for `select` elements. Need to use a `Select` or `SelectWrapper` component. (See note in `ElementCache`)

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/pages/core/admin/AuditLogMaintenancePage.java
> +        WebElement retentionTime = Locator.name("retentionTime").findWhenNeeded(this);
Use component for select.
```suggestion
        Select retentionTime = SelectWrapper.Select(Locator.name("retentionTime")).findWhenNeeded(this);
```

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/tests/AuditLogMaintenanceTest.java
> +        switchToMainWindow();
There's an existing test page for pipeline status (`PipelineStatusDetailsPage`).
```suggestion
        switchToWindow(1);
        new PipelineStatusDetailsPage(getDriver()).waitForStatus("COMPLETE");
        switchToMainWindow();
```

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/tests/AuditLogMaintenanceTest.java
> +        checker().verifyTrue("Audit log table not cleared", auditLogPage.getLogTable().getDataRowCount() == 0);
Just use a normal assertion here. The `checker` gets cranky when you don't take a screenshot after a failure.
```suggestion
        Assert.assertTrue("Audit log table not cleared", auditLogPage.getLogTable().getDataRowCount() == 0);
```

2023-03-31 21:21 UTC, labkey-tchad commented on src/org/labkey/test/tests/AuditLogMaintenanceTest.java
> +    }
Don't use the UI in `@After` and `@AfterClass` methods. It interferes with test failure handling and screenshots. This should be easy enough to do via API.
```suggestion
    @After
    public void restoreSettings()
    {
        SimplePostCommand command = new SimplePostCommand("professional", "auditLogMaintenance");
        command.setJSONObject(new JSONObject(Map.of("retentionTime", -1, "export", false)));
        command.execute(createDefaultConnection(), null);
    }
```

2023-04-03 05:55 UTC, labkey-sweta commented on src/org/labkey/test/pages/core/admin/AuditLogMaintenancePage.java
> +        waitForPage();
Done

2023-04-03 23:25 UTC, labkey-adam approved these changes

2023-04-05 17:13 UTC, labkey-tchad requested changes
`testAutomation` shouldn't reference classes in other repositories.
`ShowAdminPage` doesn't need to know about all the pages it might have links to. Modules can register all sorts of admin actions.

2023-04-05 19:14 UTC, labkey-tchad approved these changes

2023-04-12 18:12 UTC, merged