Automation test for Wiki search results show HTML source when document includes a comma
LabKey/testAutomation pull request #1665
Opened 2023-10-10 00:55 UTC by labkey-sweta

#### Rationale
Automation test for Wiki search results show HTML source when document includes a comma

Repro:

- Create an HTML wiki page with text "This is my HTML, with commas" on labkey.org (e.g., in the Staff project).
- Save
- Search for "commas" in the current folder
- Search result should not show HTML tags

https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=47814

#### Related Pull Requests
* 

#### Changes
*

2023-10-10 01:21 UTC, labkey-jeckels approved these changes

2023-10-10 01:21 UTC, labkey-jeckels commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +         :https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=48019
```suggestion
         https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=48019
```

2023-10-10 15:15 UTC, labkey-tchad requested changes

2023-10-10 15:15 UTC, labkey-tchad commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +    private final SearchHelper _searchHelper = new SearchHelper(this, SEARCH_RESULTS_QUEUE).setMaxTries(6);
These don't need to be class members if only one test is using them.

2023-10-10 15:15 UTC, labkey-tchad commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +        wikiHelper.setWikiBody(wikiContent);
If I remember correctly, the wiki helper doesn't know how to use the graphical editor. It switches to the html source tab automatically. If so, this needs to have some html tags added explicitly.
```suggestion
        wikiHelper.setWikiBody("<p>" + wikiContent + "</p>");
```

2023-10-10 15:15 UTC, labkey-tchad commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +        _searchHelper.searchFor("commas");
Make sure you're only searching within the project for this test. Don't want other tests interfering with this.

2023-10-10 20:58 UTC, labkey-tchad requested changes

2023-10-10 20:58 UTC, labkey-tchad commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +        wikiHelper.saveWikiPage();
Increment this count after saving.
```suggestion
        setFormElement(Locator.name("name"), wikiName);
        setFormElement(Locator.name("title"), wikiTitle);
        wikiHelper.setWikiBody("<p>" + wikiContent + "</p>");
        wikiHelper.saveWikiPage();
        numberOfWikiCreated++;
```

2023-10-10 20:58 UTC, labkey-tchad commented on src/org/labkey/test/tests/wiki/WikiTest.java
> +        searchFor(PROJECT_NAME, "commas", numberOfWikiCreated, wikiTitle);
This search should only show one result, right?
```suggestion
        searchFor(PROJECT_NAME, "commas", 1, wikiTitle);
```

2023-10-11 22:47 UTC, labkey-tchad approved these changes

2023-10-12 04:30 UTC, merged