Disambiguate hasSelectionColumn from hasSelectAllCheckbox
LabKey/testAutomation pull request #1927
Opened 2024-05-14 00:02 UTC by labkey-chrisj

#### Rationale
While writing test coverage for Issue 50062 (related PR) I ran into the apparently rare case where the EditableGrid has a selection column but does not have a select-all checkbox: 
<img width="375" alt="image" src="https://github.com/LabKey/testAutomation/assets/16809856/34258264-0acc-4203-83a8-7f45f34261d6">
(most editable grids that have a select-column have a select-all-checkbox, like this: 
<img width="345" alt="image" src="https://github.com/LabKey/testAutomation/assets/16809856/67e7ee54-9d9f-41f2-9d40-e06eff2904e5">

Currently, the method to select a row (`selectRow`) checks to see if there's a selection column present on the grid. The method it checks with (`hasSelectColumn`) simply checks to see if the select-all checkbox is present. Because no select-all-checkbox is present, `hasSelectColumn` wrongly returns false when `selectRow` asks if there is a selection column.

This change adds a separate method (`hasSelectAllCheckbox`) to the class, and refactors callers to use that where it's the presence of the select-all checkbox they're interested in vs. the availability of row-by-row select checkboxes in the table.

#### Related Pull Requests
tbd (pr for issue 50062 in progress)

#### Changes

- [x] new method to check for the presence of a select-all checkbox
- [x] refactor usages of hasSelectColumn to use hasSelectAllCheckbox where appropriate

2024-05-14 19:27 UTC, labkey-tchad approved these changes

2024-05-14 19:27 UTC, labkey-tchad commented on src/org/labkey/test/components/ui/grids/EditableGrid.java
> +            .withAttribute("id", "__selection__");
A future editor of this file might appreciate a comment indicating why the select-all cell and select-all checkbox are defined separately.
```suggestion
        // Some grids have an placeholder cell without a select-all checkbox
        private final Locator selectAllHeaderCellLoc = Locator.tagWithClass("th", "grid-header-cell")
            .withAttribute("id", "__selection__");
```

2024-05-15 15:54 UTC, labkey-danield requested changes
Can you validate that this is not a product bug and add a comment?

2024-05-15 15:54 UTC, labkey-danield commented
@labkey-chrisj did you validate that this isn't a product bug?

2024-05-15 17:01 UTC, labkey-chrisj commented
@labkey-nicka @labkey-alan @cnathe should it be considered a product bug if we see a grid with a selection row but without a select-all checkbox in it?

2024-05-15 17:49 UTC, labkey-chrisj commented
> @labkey-chrisj did you validate that this isn't a product bug?

Nick said in standup taht there's no reason to have it that way, he intends to add in the missing select-all checkbox in a PR already in flight, not sure which PR

2024-05-15 19:59 UTC, labkey-nicka commented
> > @labkey-chrisj did you validate that this isn't a product bug?
> 
> Nick said in standup that there's no reason to have it that way, he intends to add in the missing select-all checkbox in a PR already in flight, not sure which PR

I've addressed this with https://github.com/LabKey/labkey-ui-components/pull/1495/commits/19535282e.

2024-05-17 15:43 UTC, labkey-chrisj commented
oh well

2024-05-17 15:43 UTC, closed without merging