Fb troubleshooter 39638
LabKey/testAutomation pull request #234
Opened 2020-02-20 06:32 UTC by labkey-sweta

Automation test

PS : Section of test is commented which verifies troubleshooter cannot save changes in authentication until the issue is fixed by rosaline.

2020-02-20 15:14 UTC, labkey-adam commented
Rosaline committed her auth save fix to platform yesterday and I verified it. I just merged develop into platform/fb_troubleshooter_39638, so should be able to uncomment that test.

2020-02-20 16:17 UTC, labkey-tchad requested changes
Looks like you branched off of a different feature branch instead of `develop`. Karl's assay test changes shouldn't be in here.

2020-02-20 16:17 UTC, labkey-tchad commented on src/org/labkey/test/tests/core/security/TroubleshooterRoleTest.java
> +//                isElementPresent(Locator.button("Save and Finish")));
Validating the absence of something can be dangerous. If the button text for any of these page changes, these checks would pass regardless of troubleshooter access.
Put these `verifyFalse` checks in a separate method (`verifySiteSettingsPermissions(boolean canSave)`) and call it once as a site admin to verify that we're checking the correct buttons, then once as troubleshooter to verify that they aren't present.

2020-02-21 19:37 UTC, labkey-tchad approved these changes

2020-02-21 19:37 UTC, labkey-tchad commented on src/org/labkey/test/tests/core/security/TroubleshooterRoleTest.java
> +        goToSitePermissions();
Shouldn't need to navigate if you're using the API helper

2020-02-21 19:37 UTC, labkey-tchad commented on src/org/labkey/test/tests/core/security/TroubleshooterRoleTest.java
> +    private static final String TROUBLESHOOTER = "user@troubleshooter.test";
Avoid display name collision
```suggestion
    private static final String TROUBLESHOOTER = "troubleshooter@troubleshooter.test";
```

2020-02-22 16:48 UTC, merged