Item 7767: Automated test updates for the new error page
LabKey/testAutomation pull request #491
Opened 2020-10-05 18:30 UTC by labkey-ankurj

#### Rationale
Automated test updates for the new error page

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/1589

2020-10-06 17:55 UTC, labkey-tchad requested changes

2020-10-06 17:55 UTC, labkey-tchad commented on src/org/labkey/test/components/html/SiteNavBar.java
> +
Don't change the behavior of this method (It only navigates if ends up on a permission denied page after impersonating). It is fairly widely used and some probably expect to be on the same page after impersonating.
Does the 403 page (or whatever page we end up on) not have a link to go to home anymore?

2020-10-06 17:55 UTC, labkey-tchad commented on src/org/labkey/test/tests/SecurityTest.java
> +        assertElementPresent(Locators.labkeyErrorSubHeading.withText("Registration is not enabled."));
This check should be specific. We know what page we should end up on. If timing is a problem, we can wait for the error.
```suggestion
        waitForElement(Locators.labkeyErrorSubHeading.withText("Registration is not enabled."));
```

2020-10-06 17:55 UTC, labkey-tchad commented on src/org/labkey/test/BaseWebDriverTest.java
> +    protected static final String NOT_FOUND_ERROR = "notFound";
Move `PERMISSION_ERROR` and `NOT_FOUND_ERROR` to `SecurityTest`. The only other place that uses `PERMISSION_ERROR` is an unused method, which can be removed: `BaseWebDriverTest.assertAtUserUserLacksPermissionPage`.

2020-10-06 17:59 UTC, labkey-ankurj commented on src/org/labkey/test/components/html/SiteNavBar.java
> +
We do not have home button on the error page anymore. Should I check for the response code from the title of the page and then route to home?

2020-10-06 19:41 UTC, labkey-tchad commented on src/org/labkey/test/components/html/SiteNavBar.java
> +
Yeah. And just click the logo in the upper-left. I'd rather not move `goToHome` into `WebDriverWrapper`.

2020-10-07 23:34 UTC, labkey-tchad reviewed
A couple of questions.
 - In `Crawler.isIgnoredError`, we ignore 404s from modules that aren't enabled in the current container. Should we update that check or do we think 404 is an inappropriate response for those actions? It probably isn't appropriate since we have links to all modules in the admin menu, regardless of whether they are enabled.
 - Is `Locator.css("table.server-error")` still valid? Its used in `Crawler.checkForServerError` and `Crawler.crawlLink`.

2020-10-08 00:30 UTC, labkey-jeckels commented
@labkey-tchad An action from an inactive module won't automatically return a 404. Most should return 200 and work OK. For example, neither Study nor Flow is enabled in this folder:

https://www.labkey.org/home/study-begin.view?

https://www.labkey.org/home/flow-begin.view?

I see exactly one spot in the code that returns a 404 with the message about a module not being enabled, in a MS2 protein search action.

2020-10-08 15:49 UTC, labkey-ankurj commented
@labkey-tchad I think `Locator.css("table.server-error")` is still valid because that is still used in WebPartErrorRenderer.

2020-10-09 02:00 UTC, labkey-ankurj commented
@labkey-tchad all the tests passed. Let me know if there are changes to be made.

2020-10-09 17:26 UTC, labkey-tchad approved these changes

2020-10-09 18:06 UTC, merged