Update bulk insert dialog to allow titles not specific to Samples
LabKey/testAutomation pull request #656
Opened 2021-03-05 17:10 UTC by labkey-chrisj

#### Rationale
To support entity bulk insert of assay run data, the EntityBulkInsertDialog can't have a hard-coded title specific to SampleTypes.  This parameterizes the title of this shared component wrapper, and calls for updating calling page classes.

#### Related Pull Requests
Biologics https://github.com/LabKey/biologics/pull/816
SampleManager

#### Changes
Allow the caller to specify the title of the EntityBulkInsertDialog

2021-03-05 23:56 UTC, labkey-tchad requested changes
Tests shouldn't have to know the title of the dialog, that's the whole point of having components. I would say just find a the modal dialog regardless of title or find a partial title value that works more broadly (Maybe just `"Bulk"` would work)

2021-03-06 00:32 UTC, labkey-chrisj commented
What I've done requires the page to know the title, which I figured would be acceptable.
The original state here was hard-coded to only be useful for bulk uploads of SampleType, which also kind of defeats the point of having a shared component able to handle cases that aren't the one it's hard-coded for.

Okay, I'll go back to hard-coding something else that will hopefully work for both known cases, right up until the point where we want to use this thing for anything else

2021-03-08 17:37 UTC, labkey-chrisj commented
Without this change, EntityBulkInsertDialog cannot be used for assay data in Biologics and should perhaps be called SampleTypeBulkInsertDialog

2021-03-08 17:51 UTC, labkey-tchad approved these changes

2021-03-08 19:55 UTC, merged