Test coverage for issue42857
LabKey/testAutomation pull request #768
Opened 2021-06-18 19:02 UTC by labkey-chrisj

#### Rationale
One of our clients wants to bulk-import samples using a nameExpression that can resolve existing values via a lookup to another domain.  This test attempts to do that, and in the attempt appears to have found an [adjacent issue ](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=43394)

#### Related Pull Requests
n/a

#### Changes
just the new test case

2021-06-21 18:06 UTC, labkey-tchad commented on src/org/labkey/test/tests/SampleTypeNameExpressionTest.java
> +                        new FieldDefinition("Noun", FieldDefinition.ColumnType.String)))
The correct pattern to set the type of a lookup is to call `setTableType`. This `setRangeURI` isn't necessary.

2021-06-21 18:07 UTC, labkey-tchad commented on src/org/labkey/test/tests/SampleTypeNameExpressionTest.java
> +        FieldDefinition.LookupInfo colorsLookup = new FieldDefinition.LookupInfo(getProjectName(), "lists", lookupList);
```suggestion
        FieldDefinition.LookupInfo colorsLookup = new FieldDefinition.LookupInfo(getProjectName(), "lists", lookupList).setTableType(FieldDefinition.ColumnType.Integer);
```

2021-06-21 21:39 UTC, labkey-tchad requested changes

2021-06-21 21:39 UTC, labkey-tchad commented on src/org/labkey/test/params/FieldDefinition.java
> +
Don't need this now, right?
```suggestion
```

2021-06-21 23:37 UTC, labkey-chrisj commented on src/org/labkey/test/params/FieldDefinition.java
> +
Let's hope you're right

2021-06-22 17:19 UTC, labkey-tchad approved these changes

2021-06-22 17:21 UTC, merged