Response Server UI
LabKey/testAutomation pull request #813
Opened 2021-07-26 16:56 UTC by RosalineP

#### Rationale
Test changes supporting consolidating settings and removing dependency on Folder Management Module Properties feature, improving usability by offering instead a more clear form with added validation and guidance.

#### Related Pull Requests
* https://github.com/FDA-MyStudies/Response/pull/28

#### Changes
* Add helper to reach Response Server Admin UI page
* Add helper for setting Response Server Configurations

2021-07-26 23:10 UTC, labkey-adam commented on src/org/labkey/test/BaseWebDriverTest.java
> +    public void setResponseServerConfigurations(LinkedHashMap<String, String> props)
I'll let @labkey-tchad weigh in on this, but it doesn't seem right that `BaseWebDriverTest` should know anything about the response server config details. It knows about module properties, but that's a very generic mechanism.

2021-07-26 23:11 UTC, labkey-adam commented on src/org/labkey/test/pages/core/admin/ShowAdminPage.java
> +    public void clickResponseServerConfiguration()
I guess there's precedent for `ShowAdminPage` knowing about all the module-specific links...

2021-07-27 17:49 UTC, labkey-tchad requested changes
Adam is correct. Except for the most core modules; module-specific test functionality should live in that module. I left some feedback here but these changes should go in the Response repository in a helper class or a page class for `ServerConfigurationAction`

2021-07-27 17:49 UTC, labkey-tchad commented on src/org/labkey/test/BaseWebDriverTest.java
> +        assertTextNotPresent("Metadata Directory path is invalid");
Checking for the non-existence of text is not reliable (somebody might change the wording of an error).
You should be able to do something like `assertElementNotPresent(Locators.labkeyError)` to catch any of these.

2021-07-27 17:49 UTC, labkey-tchad commented on src/org/labkey/test/BaseWebDriverTest.java
> +        clickButton("Save and Finish", 0);
Does "Save and Finish" not navigate? Failing to wait for page loads that occur is a frequent source of intermittent failures.
```suggestion
        clickButton("Save and Finish");
```

2021-07-28 04:08 UTC, RosalineP commented on src/org/labkey/test/BaseWebDriverTest.java
> +        assertTextNotPresent("Metadata Directory path is invalid");
Ahhh makes sense, done!

2021-07-28 16:31 UTC, labkey-tchad requested changes
Adam is correct. Except for the most core modules; module-specific test functionality should live in that module. These changes should go in the Response repository in a helper class or a page class for ServerConfigurationAction.
This branch can be deleted.

2021-07-28 17:09 UTC, RosalineP commented
Changes moved to `Response` branch!

2021-07-28 17:09 UTC, closed without merging