Issue Definition designer Automation test
LabKey/testAutomation pull request #844
Opened 2021-08-19 08:18 UTC by labkey-sweta

#### Rationale
1. IssuesAdminTest.testCommentSortDirection
2. IssueAdminTest.testRelatedIssuesComments
3. IssueAdminTest.testProtectedFields
4. IssuesTest.defaultAssignedToTest

#### Related Pull Requests
* 

#### Changes
*

2021-08-19 15:24 UTC, labkey-tchad requested changes
The `newElementCache` methods should remain protected, not sure why they're getting switched to public here.

2021-08-19 21:11 UTC, cnathe reviewed
From a test case point-of-view, this looks to cover the items that we discussed. Thanks.

2021-08-19 21:11 UTC, cnathe commented on src/org/labkey/test/tests/issues/IssuesAdminTest.java
> +        checker().verifyTrue("Resolution should be disabled", domainFormPanel.getField("Resolution").isFieldProtected());
may be worth adding a couple of checks that some of the other default fields are not protected

2021-08-19 21:11 UTC, cnathe commented on src/org/labkey/test/tests/issues/IssuesTest.java
>          // TODO: compare user dropdown list between admin and new issues page
is this TODO still needed or is this covered in the check at line 843? maybe I am misreading it and there is more to do.

2021-08-26 15:49 UTC, labkey-sweta commented on src/org/labkey/test/tests/issues/IssuesAdminTest.java
> +        checker().verifyTrue("Resolution should be disabled", domainFormPanel.getField("Resolution").isFieldProtected());
Done

2021-08-26 15:53 UTC, labkey-sweta commented on src/org/labkey/test/tests/issues/IssuesTest.java
>          // TODO: compare user dropdown list between admin and new issues page
I just read the second part or TODO worth adding  the test for "extend test to check validate full user selection list based on group selection" ?


> is this TODO still needed or is this covered in the check at line 843? maybe I am misreading it and there is more to do.

2021-08-26 16:06 UTC, labkey-tchad commented on src/org/labkey/test/components/domain/DomainFieldRow.java
> +        ;
```suggestion
        elementCache().expectedVocabularyButton().click();
```

2021-08-26 16:11 UTC, labkey-tchad approved these changes

2021-08-26 17:06 UTC, cnathe commented on src/org/labkey/test/tests/issues/IssuesTest.java
>          // TODO: compare user dropdown list between admin and new issues page
Got it.

2021-08-26 19:02 UTC, cnathe approved these changes

2021-08-27 02:23 UTC, merged